# install-services.yml

---
- hosts: jenk
  become: true
  tasks:
    - name: Updating all existing packages...
      yum:
        name: '*'
        state: latest
        update_only: yes
  
    - name: Installing GIT...
      yum:
        name: git
        state: present
    
    - name: Installing docker...
      shell:
        cmd: amazon-linux-extras install docker
    - name: Starting docker...
      systemd:
        name: docker
        state: started
    - name: enabling docker...
      systemd:
        name: docker
        enabled: true
    - name: Enabling ec2-user to use docker without sudo
      shell:
        cmd: sudo usermod -a -G docker ec2-user

    - name: Downloading docker compose. This is needed for jenkins CasC...
      shell:
        cmd: sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - name: Make docker compose executable
      shell:
        cmd: sudo chmod +x /usr/local/bin/docker-compose


